version: "3.3"
services:
  client:
    image: lrth06/apiclient
    container_name: apiclient
    ports:
      - "80:80"

  server:
    image: lrth06/api
    container_name: api
    ports:
      - "5000:5000"
    env_file:
      - ./.env.sample
    depends_on:
      - "mongodb"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/data/db"
